<a href="https://colab.research.google.com/github/paco415/practica/blob/main/Morelos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Empieza en depto.1

In [1]:
import pandas as pd
import numpy as np
from tabulate import tabulate

In [2]:
datos = {"Depto": [1,2,"A",3,4,5,6,"3A"], "Dia_Pago": [8,17,21,30,7,15,1,16],
       "Pago": [4350,4500,3500,4650,4500,4150,3800,4350],
        "Acumulado": [4350,7350,10850,15500,20000,24150,27950,33800],
        "Ingreso": ["Sept","Febrero","No","Octubre","Febrero","Marzo","Junio","Febrero"],
        "Nombre": ["Martina","María","ALEJANDRO","Natalia","Norma","Felipe","Eduardo","Leticia"]}

df = pd.DataFrame(data = datos)
df

  Depto  Dia_Pago  Pago  Acumulado  Ingreso     Nombre
0     1         8  4350       4350     Sept    Martina
1     2        17  4500       7350  Febrero      María
2     A        21  3500      10850       No  ALEJANDRO
3     3        30  4650      15500  Octubre    Natalia
4     4         7  4500      20000  Febrero      Norma
5     5        15  4150      24150    Marzo     Felipe
6     6         1  3800      27950    Junio    Eduardo
7    3A        16  4350      33800  Febrero    Leticia

In [3]:
Suma = df["Pago"].sum()
Suma

33800

#### Tabulate

In [4]:
datos = {"Depto": [1,2,"A",3,4,5,6,"3A"], "Dia_Pago": [8,17,21,30,7,15,1,16],
       "Pago": [4350,4500,3500,4650,4500,4150,3800,4350],
        "Acumulado": [4350,7350,10850,15500,20000,24150,27950,33800],
        "Ingreso": ["Sept","Febrero","No","Octubre","Febrero","Marzo","Junio","Febrero"],
        "Nombre": ["Martina","María","ALEJANDRO","Natalia","Norma","Felipe","Eduardo","Leticia"]}

df = pd.DataFrame(data = datos)
df

print(tabulate(df,headers="keys",tablefmt="fancy_grid",numalign="center",stralign="center))"))

╒════╤═════════╤════════════╤════════╤═════════════╤═══════════╤═══════════╕
│    │   Depto │  Dia_Pago  │  Pago  │  Acumulado  │   Ingreso │    Nombre │
╞════╪═════════╪════════════╪════════╪═════════════╪═══════════╪═══════════╡
│ 0  │ 1       │     8      │  4350  │    4350     │ Sept      │ Martina   │
├────┼─────────┼────────────┼────────┼─────────────┼───────────┼───────────┤
│ 1  │ 2       │     17     │  4500  │    7350     │ Febrero   │ María     │
├────┼─────────┼────────────┼────────┼─────────────┼───────────┼───────────┤
│ 2  │ A       │     21     │  3500  │    10850    │ No        │ ALEJANDRO │
├────┼─────────┼────────────┼────────┼─────────────┼───────────┼───────────┤
│ 3  │ 3       │     30     │  4650  │    15500    │ Octubre   │ Natalia   │
├────┼─────────┼────────────┼────────┼─────────────┼───────────┼───────────┤
│ 4  │ 4       │     7      │  4500  │    20000    │ Febrero   │ Norma     │
├────┼─────────┼────────────┼────────┼─────────────┼───────────┼───────────┤
│ 5  │ 5       │     15     │  4150  │    24150    │ Marzo     │ Felipe    │
├────┼─────────┼────────────┼────────┼─────────────┼───────────┼───────────┤
│ 6  │ 6       │     1      │  3800  │    27950    │ Junio     │ Eduardo   │
├────┼─────────┼────────────┼────────┼─────────────┼───────────┼───────────┤
│ 7  │ 3A      │     16     │  4350  │    33800    │ Febrero   │ Leticia   │
╘════╧═════════╧════════════╧════════╧═════════════╧═══════════╧═══════════╛

#### Empieza en depto. 5

#### Formato Normal

##### A partir del dia 8 del mes

In [5]:
import pandas as pd
import numpy as np
from tabulate import tabulate

In [6]:
datos = {"Depto": [5,"3A",2,"A",3,6,4,1], "Dia_Pago": [15,16,17,21,30,1,7,8],
       "Pago": [4150,4360,4500,3500,4650,3800,4500,4350],
       "Acumulado": [4150,8500,13000,16500,21150,24950,29450,33810],
         "Cuenta": ["Pau","Pau","Pau","Paco",0,0,0,0],
       "Ingreso": ["Marzo","Febrero","Febrero","No","Octubre","Junio","Febrero","Sept"],
        "Nombre": ["Felipe","Leticia","María","ALEJANDRO","Natalia","Eduardo","Norma","Martina"]}

df = pd.DataFrame(data = datos)
df

  Depto  Dia_Pago  Pago  Acumulado Cuenta  Ingreso     Nombre
0     5        15  4150       4150    Pau    Marzo     Felipe
1    3A        16  4360       8500    Pau  Febrero    Leticia
2     2        17  4500      13000    Pau  Febrero      María
3     A        21  3500      16500   Paco       No  ALEJANDRO
4     3        30  4650      21150      0  Octubre    Natalia
5     6         1  3800      24950      0    Junio    Eduardo
6     4         7  4500      29450      0  Febrero      Norma
7     1         8  4350      33810      0     Sept    Martina

In [7]:
Suma = df["Pago"].sum()
Suma

33810

#### Tabulate

In [8]:
import pandas as pd
import numpy as np
from tabulate import tabulate

#### Tabulate

In [9]:
datos = {"Depto": [5,"3A",2,"A",3,6,4,1], "Dia_Pago": [15,16,17,21,30,1,7,8],
       "Pago": [4150,4360,4500,3500,4650,3800,4500,4350],
       "Acumulado": [4150,8650,13010,16510,21160,24960,29460,33810],
       "Cuenta": ["Pau","Pau","Pau","Paco",0,0,0,0],
       "Ingreso": ["Marzo","Febrero","Febrero","No","Octubre","Junio","Febrero","Sept"],
       "Nombre": ["Felipe","Leticia","María","ALEX","Natalia","Eduardo","Norma","Martina"],
        }

df = pd.DataFrame(data = datos)
df

print(tabulate(df,headers="keys",tablefmt="fancy_grid",numalign="center",
               stralign="center))"))

╒════╤═════════╤════════════╤════════╤═════════════╤══════════╤═══════════╤══════════╕
│    │   Depto │  Dia_Pago  │  Pago  │  Acumulado  │   Cuenta │   Ingreso │   Nombre │
╞════╪═════════╪════════════╪════════╪═════════════╪══════════╪═══════════╪══════════╡
│ 0  │ 5       │     15     │  4150  │    4150     │ Pau      │ Marzo     │ Felipe   │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼──────────┤
│ 1  │ 3A      │     16     │  4360  │    8650     │ Pau      │ Febrero   │ Leticia  │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼──────────┤
│ 2  │ 2       │     17     │  4500  │    13010    │ Pau      │ Febrero   │ María    │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼──────────┤
│ 3  │ A       │     21     │  3500  │    16510    │ Paco     │ No        │ ALEX     │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼──────────┤
│ 4  │ 3       │     30     │  4650  │    21160    │ 0        │ Octubre   │ Natalia  │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼──────────┤
│ 5  │ 6       │     1      │  3800  │    24960    │ 0        │ Junio     │ Eduardo  │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼──────────┤
│ 6  │ 4       │     7      │  4500  │    29460    │ 0        │ Febrero   │ Norma    │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼──────────┤
│ 7  │ 1       │     8      │  4350  │    33810    │ 0        │ Sept      │ Martina  │
╘════╧═════════╧════════════╧════════╧═════════════╧══════════╧═══════════╧══════════╛

#### Diario

In [10]:
import pandas as pd
import numpy as np
from tabulate import tabulate

In [11]:
datos = {"Depto": [5,"3A",2,"A",3,6,4,1], "Dia_Pago": [15,16,17,21,30,1,7,8],
       "Pago": [4150,4360,4500,0,0,0,0,0],
       "Acumulado": [4150,8660,13010,16510,21160,24960,29460,33810],
        "Cuenta": ["Pau","Pau","Pau","Paco",0,0,0,0],
       "Ingreso": ["Marzo","Febrero","Febrero","No","Octubre","Junio","Febrero","Sept"],
        "Nombre": ["Felipe","Leticia","María","ALEJANDRO","Natalia","Eduardo","Norma","Martina"]}

df = pd.DataFrame(data = datos)
df

  Depto  Dia_Pago  Pago  Acumulado Cuenta  Ingreso     Nombre
0     5        15  4150       4150    Pau    Marzo     Felipe
1    3A        16  4360       8660    Pau  Febrero    Leticia
2     2        17  4500      13010    Pau  Febrero      María
3     A        21     0      16510   Paco       No  ALEJANDRO
4     3        30     0      21160      0  Octubre    Natalia
5     6         1     0      24960      0    Junio    Eduardo
6     4         7     0      29460      0  Febrero      Norma
7     1         8     0      33810      0     Sept    Martina

In [12]:
Suma = df["Pago"].sum()
Suma

13010

#### Diario

#### Tabulate

In [13]:
import pandas as pd
import numpy as np
from tabulate import tabulate

In [14]:
datos = {"Depto": [5,"3A",2,"A",3,6,4,1], "Dia_Pago": [15,16,17,21,30,1,7,8],
       "Pago": [4150,4360,4500,0,0,0,0,0],
       "Acumulado": [4150,8660,13010,16510,21160,24960,29460,33810],
        "Cuenta": ["Pau","Pau","Pau","Paco",0,0,0,0],
       "Ingreso": ["Marzo","Febrero","Febrero","No","Octubre","Junio","Febrero","Sept"],
       "Nombre": ["Felipe","Leticia","María","ALEJANDRO","Natalia","Eduardo","Norma","Martina"]}

df = pd.DataFrame(data = datos)
df

print(tabulate(df,headers="keys",tablefmt="fancy_grid",numalign="center",
               stralign="center"))

╒════╤═════════╤════════════╤════════╤═════════════╤══════════╤═══════════╤═══════════╕
│    │  Depto  │  Dia_Pago  │  Pago  │  Acumulado  │  Cuenta  │  Ingreso  │  Nombre   │
╞════╪═════════╪════════════╪════════╪═════════════╪══════════╪═══════════╪═══════════╡
│ 0  │    5    │     15     │  4150  │    4150     │   Pau    │   Marzo   │  Felipe   │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼───────────┤
│ 1  │   3A    │     16     │  4360  │    8660     │   Pau    │  Febrero  │  Leticia  │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼───────────┤
│ 2  │    2    │     17     │  4500  │    13010    │   Pau    │  Febrero  │   María   │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼───────────┤
│ 3  │    A    │     21     │   0    │    16510    │   Paco   │    No     │ ALEJANDRO │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼───────────┤
│ 4  │    3    │     30     │   0    │    21160    │    0     │  Octubre  │  Natalia  │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼───────────┤
│ 5  │    6    │     1      │   0    │    24960    │    0     │   Junio   │  Eduardo  │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼───────────┤
│ 6  │    4    │     7      │   0    │    29460    │    0     │  Febrero  │   Norma   │
├────┼─────────┼────────────┼────────┼─────────────┼──────────┼───────────┼───────────┤
│ 7  │    1    │     8      │   0    │    33810    │    0     │   Sept    │  Martina  │
╘════╧═════════╧════════════╧════════╧═════════════╧══════════╧═══════════╧═══════════╛

In [15]:
Suma = df["Pago"].sum()
Suma

13010

#### Balance personal

In [16]:
import pandas as pd
import numpy as np
from tabulate import tabulate

In [17]:
datos = {"A":["Renta","Super","Elvira","ATT","Izzi","Sky","Air","Cel","Tv","Gasolina","Cajero",
             "Otros"],
         "Pagos": [4300,3000,6000,650, 520,750,5300,700,650,2400,2800,1000],
         "Concepto": ["IMSS","Utilidad",0,0,0,0,0,0,0,0,0,"Bienestar"],
        "Ingresos": [14000,7500,0,0,0,0,0,0,0,0,0,3000]}
df = pd.DataFrame(data=datos)
df

           A  Pagos   Concepto  Ingresos
0      Renta   4300       IMSS     14000
1      Super   3000   Utilidad      7500
2     Elvira   6000          0         0
3        ATT    650          0         0
4       Izzi    520          0         0
5        Sky    750          0         0
6        Air   5300          0         0
7        Cel    700          0         0
8         Tv    650          0         0
9   Gasolina   2400          0         0
10    Cajero   2800          0         0
11     Otros   1000  Bienestar      3000

In [18]:
Suma_1 = df["Pagos"].sum()
Suma_1

28070

In [19]:
Suma_2 = df["Ingresos"].sum()
Suma_2

24500

In [20]:
Suma_2 - Suma_1

-3570

#### Tabulate

In [21]:
datos = {"A":["Renta","Super","Elvira","ATT","Izzi","Sky","Air","Cel","Tv","Gasolina","Cajero",
             "Otros"],
         "Pagos": [4300,3000,6000,650, 520,750,5300,700,650,2400,2800,1000],
         "Concepto": ["IMSS","Utilidad",0,0,0,0,0,0,0,0,0,"Bienestar"],
        "Ingresos": [14000,7500,0,0,0,0,0,0,0,0,0,3000]}
df = pd.DataFrame(data=datos)
df

print(tabulate(df,headers="keys",tablefmt="fancy_grid",numalign="center",
               stralign="center"))

╒════╤══════════╤═════════╤════════════╤════════════╕
│    │    A     │  Pagos  │  Concepto  │  Ingresos  │
╞════╪══════════╪═════════╪════════════╪════════════╡
│ 0  │  Renta   │  4300   │    IMSS    │   14000    │
├────┼──────────┼─────────┼────────────┼────────────┤
│ 1  │  Super   │  3000   │  Utilidad  │    7500    │
├────┼──────────┼─────────┼────────────┼────────────┤
│ 2  │  Elvira  │  6000   │     0      │     0      │
├────┼──────────┼─────────┼────────────┼────────────┤
│ 3  │   ATT    │   650   │     0      │     0      │
├────┼──────────┼─────────┼────────────┼────────────┤
│ 4  │   Izzi   │   520   │     0      │     0      │
├────┼──────────┼─────────┼────────────┼────────────┤
│ 5  │   Sky    │   750   │     0      │     0      │
├────┼──────────┼─────────┼────────────┼────────────┤
│ 6  │   Air    │  5300   │     0      │     0      │
├────┼──────────┼─────────┼────────────┼────────────┤
│ 7  │   Cel    │   700   │     0      │     0      │
├────┼──────────┼─────────┼────────────┼────────────┤
│ 8  │    Tv    │   650   │     0      │     0      │
├────┼──────────┼─────────┼────────────┼────────────┤
│ 9  │ Gasolina │  2400   │     0      │     0      │
├────┼──────────┼─────────┼────────────┼────────────┤
│ 10 │  Cajero  │  2800   │     0      │     0      │
├────┼──────────┼─────────┼────────────┼────────────┤
│ 11 │  Otros   │  1000   │ Bienestar  │    3000    │
╘════╧══════════╧═════════╧════════════╧════════════╛

In [22]:
Suma_2 - Suma_1

-3570

#### Ejercicio para acumulados

In [23]:
import pandas as pd
import numpy as np
from tabulate import tabulate

In [24]:
datos = {"Depto": [5,"3A",2,"A",3,6,4,1], "Dia_Pago": [15,16,17,21,30,1,7,8],
       "Pago": [4150,4360,4500,0,0,0,0,0],
       "Acumulado": [4150,8660,13010,16510,21160,24960,29460,33810],
        "Cuenta": ["Pau","Pau","Pau","Paco",0,0,0,0],
       "Ingreso": ["Marzo","Febrero","Febrero","No","Octubre","Junio","Febrero","Sept"],
        "Nombre": ["Felipe","Leticia","María","ALEJANDRO","Natalia","Eduardo","Norma","Martina"]}

df = pd.DataFrame(data = datos)
df

  Depto  Dia_Pago  Pago  Acumulado Cuenta  Ingreso     Nombre
0     5        15  4150       4150    Pau    Marzo     Felipe
1    3A        16  4360       8660    Pau  Febrero    Leticia
2     2        17  4500      13010    Pau  Febrero      María
3     A        21     0      16510   Paco       No  ALEJANDRO
4     3        30     0      21160      0  Octubre    Natalia
5     6         1     0      24960      0    Junio    Eduardo
6     4         7     0      29460      0  Febrero      Norma
7     1         8     0      33810      0     Sept    Martina

In [25]:
df.iloc[1 ,3 : 6]

Acumulado       8660
Cuenta           Pau
Ingreso      Febrero
Name: 1, dtype: object